name: iOS Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Обновили до v4
      - uses: actions/checkout@v4

      # Обновили до v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest
          gomobile init

      # Очень важный шаг: скачиваем зависимости перед сборкой
      - name: Go Mod Tidy
        working-directory: ./plotix_core
        run: go mod tidy

      - name: Build iOS
        run: |
          mkdir -p mobile_out
          # Убедитесь, что путь ./plotix_core/mobile корректен относительно корня репозитория
          gomobile bind -v -target=ios -o mobile_out/PlotixCore.xcframework ./plotix_core/mobile

      # Обновили до v4 (исправляет вашу ошибку)
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PlotixCore-iOS-Framework
          path: mobile_out/PlotixCore.xcframework